// update (existing) blog post [id]
// generated by chatgpt
import prisma from "@/utils/db";
export default async function handler(req, res) {
    const { method } = req;
    const { id } = req.query; // get the id from the query parameters

    if (method === 'PUT') {
        // update blog post
        const { title, description, tags } = req.body;

        try {
            const updatedPost = await prisma.blogPost.update({
                where: { id: Number(id) }, // find post by post id
                data: {  // these can be updated (edited); 
                        // can update some or all fields based on what is sent in req
                    title,
                    description,
                    tags,
                },
            });
            res.status(200).json(updatedPost);
        } catch (error) {
            res.status(500).json({ error: 'Could not update blog post' });
        }
    } else if (method === 'DELETE') {
        // delete blog post
        try {
            await prisma.blogPost.delete({  
                where: { id: Number(id) }, 
            });
            res.status(204).end(); // No content response
        } catch (error) {
            res.status(500).json({ error: 'Could not delete blog post' });
        }
    } else {
        // Method not allowed
        res.setHeader('Allow', ['PUT']);
        res.status(405).end(`Method ${method} Not Allowed`);
    }
}